# Generated by Django 6.0.6 on 2026-07-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
    ]
